# Generated by Django 4.2.16 on 2025-02-05 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 20, 39, 36, 228292, tzinfo=datetime.timezone.utc)),
        ),
    ]
